### ISSUE TITLE
[FEATURE] Implements AtlasLineageDispatcher to send lineage to Apache Atlas

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#4814]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Implements `AtlasLineageDispatcher` to send lineage to Apache Atlas.

### Motivation

Apache Atlas is a widely used data governance service. I want to implement a `AtlasLineageDispatcher` in kyuubi-spark-lineage plugin to send lineage to Atlas.

### Describe the solution

Steps:
+ Introduce atlas client dependencies
+ Convert lineage object to atlas `spark_process` entity
+ Send lineage atlas entity to atlas via atlas client

atlas spark model: https://github.com/apache/atlas/blob/master/addons/models/1000-Hadoop/1100-spark_model.json

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Oh, interesting, the reason should be: AtlasClient is initialized lazily, and it will add a shutdown hook during initialization, issue happens if it is initialized during JVM shutting down.

but if we catch and swallow the exception on `registerCleanupShutdownHook`, `AtlasClient` may not be able to close properly and results to leak (e.g., non-daemon threads might blocks driver JVM from exiting), so we may need to find another way to init the AtlasClient earlier

**Comment by xc-jianghan** [comment]
Thank you very much for taking the time to reply to a student like me despite your busy schedule. Your judgment makes a lot of sense. When I was using AI to help me learn, it also suggested the same direction. But since you’re the creator, you understand this architecture better than anyone.

Following the AI’s suggestions, I made several changes and recompiled multiple times. The main changes were:
1.&nbsp;
removing the lazy initialization, and

2.&nbsp;
creating the AtlasClient earlier.



However, neither approach was able to solve the issue.

My current environment is Hadoop 3.4.0 + Spark 3.5.3 + Atlas 2.4.0. Could you give me some guidance? I’m willing to pay for consulting, and I would be very grateful for any advice you can share.






                    Cheng ***@***.***&gt;&nbsp;在 2026年2月7日 周六 18:59 写道：

pan3793 left a comment (apache/kyuubi#4814)
 
Oh, interesting, the reason should be: AtlasClient is initialized lazily, and it will add a shutdown hook during initialization.
 
but if we catch and swallow the exception on registerCleanupShutdownHook, AtlasClient may not be able to close properly and results to leak (e.g., non-daemon threads might blocks driver JVM from exiting), so we may need to find another way to init the AtlasClient earlier

**Comment by xc-jianghan** [comment]
Hi Cheng Pan,

Thank you for the suggestion about avoiding potential leaks.

So my understanding is: I should initialize the Atlas client earlier, and also return a flag from getClient() to indicate whether the caller should explicitly close the client after use (when the shutdown hook cannot be registered). Would a simple approach like the following make sense?



import org.apache.hadoop.util.ShutdownHookManager object AtlasClient { &nbsp; @volatile private var cached: AtlasRestClient = _ &nbsp; def getClient(/* conf / props */): (AtlasRestClient, Boolean) = { &nbsp; &nbsp; if (cached != null) return (cached, false) &nbsp; &nbsp; this.synchronized { &nbsp; &nbsp; &nbsp; if (cached != null) return (cached, false) &nbsp; &nbsp; &nbsp; val tmp = new AtlasRestClient(/* conf / props */) &nbsp; &nbsp; &nbsp; val hookOk = tryRegisterCleanupShutdownHook(tmp) &nbsp; &nbsp; &nbsp; if (hookOk) { &nbsp; &nbsp; &nbsp; &nbsp; cached = tmp &nbsp; &nbsp; &nbsp; &nbsp; (cached, false) &nbsp; &nbsp; &nbsp; } else { &nbsp; &nbsp; &nbsp; &nbsp; (tmp, true) // caller should close after use &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; } &nbsp; private def tryRegisterCleanupShutdownHook(client: AtlasRestClient): Boolean = { &nbsp; &nbsp; val shm = ShutdownHookManager.get() &nbsp; &nbsp; if (shm.isShutdownInProgress) return false &nbsp; &nbsp; try { &nbsp; &nbsp; &nbsp; shm.addShutdownHook( &nbsp; &nbsp; &nbsp; &nbsp; new Thread("kyuubi-atlas-client-cleanup") { &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; override def run(): Unit = client.close() &nbsp; &nbsp; &nbsp; &nbsp; }, &nbsp; &nbsp; &nbsp; &nbsp; /* priority */ 0 &nbsp; &nbsp; &nbsp; ) &nbsp; &nbsp; &nbsp; true &nbsp; &nbsp; } catch { &nbsp; &nbsp; &nbsp; case _: IllegalStateException =&gt; &nbsp; &nbsp; &nbsp; &nbsp; false &nbsp; &nbsp; } &nbsp; } } 


And then update the dispatcher to close the client only when needed:



val (client, shouldClose) = AtlasClient.getClient(...) try { &nbsp; client.send(...) } finally { &nbsp; if (shouldClose) { &nbsp; &nbsp; client.close() &nbsp; } } 


My question: with this change, can we ensure that in the spark-sql -e single-statement case, the lineage is sent successfully before Spark exits? Or is it still possible that the driver shuts down before the listener/dispatcher has a chance to run?

Thanks again!





                    Cheng ***@***.***&gt;&nbsp;在 2026年2月7日 周六 20:29 写道：

pan3793 left a comment (apache/kyuubi#4814)
 
a simple approach:
   object AtlasClient {   ... -   def getClient(): AtlasClient = { +   def getClient(): (AtlasClient, Boolean) = {   ...   }
 
Add an additional flag in the return value to indicate whether the caller should close it AtlasClient after using it.

**Comment by xc-jianghan** [comment]
Hello, I have resolved the previous issue, but I encountered a new error while using it. The error message is:

26/02/09 04:40:50 WARN AtlasLineageDispatcher: Send lineage to atlas failed. org.apache.atlas.AtlasServiceException: Metadata service API ***@***.*** failed with status 404 (Not Found) Response Body ({"errorCode":"ATLAS-404-00-00A","errorMessage":"Referenced entity AtlasObjectId{guid='null', typeName='hive_column', ***@***.***}} is not found"})

My guess is that this is caused by derived columns in the SQL such as count(1)&nbsp;, which do not reference a specific column name. Should I optimize the code to filter out abnormal/non-standard column information like _count_ when uploading lineage?



                    Cheng ***@***.***&gt;&nbsp;在 2026年2月7日 周六 21:27 写道：

pan3793 left a comment (apache/kyuubi#4814)
 
code block is malformed, for code details, you can send a PR directly.
  
I should initialize the Atlas client earlier,
  
not necessary then
  
and also return a flag from getClient() to indicate whether the caller should explicitly close the client after use (when the shutdown hook cannot be registered).
  
correct. this ensures no resouce leak.
