### ISSUE TITLE
[FEATURE] kyuubi thrift支持hive metastore协议兼容；starrocks外部表直接对接kyuubi

### ISSUE THREAD

**Issue by zyclove** [apache/kyuubi#6013]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

CREATE EXTERNAL CATALOG hive_catalog_test
PROPERTIES(
     "type"="hive", 
     "hive.metastore.type" = "hive",
     "hive.metastore.uris"="thrift://172.30.15.11:10010"
     );

希望上面直接对接kyuubi  "hive.metastore.uris"="thrift://172.30.15.11:10010"

https://kyuubi.readthedocs.io/en/master/deployment/hive_metastore.html

或者kyuubi有自己的元数据管理，直接对接。

### Motivation

starrocks /  doris
            ||
       kyubbi(metaserver)
            ||
 hive/hudi/iceberg/paimon

### Describe the solution

如上

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
> kyuubi thrift支持hive metastore协议兼容

I don't fully understand it because it looks like there is a grammatical error in this sentence.

I suppose you mean "我认为 Kyuubi 的 Thrift API 与 Hive Metastore 兼容，所以 Kyuubi 可以作为 Hive Metastore 的替代品", this is **NOT** true, this is no such description on Kyuubi's docs and public articles. Kyuubi implemented a HiveServer2-compatible Thrift API, not Hive Metastore, they are two completely different components.

> https://kyuubi.readthedocs.io/en/master/deployment/hive_metastore.html

this is a guide about how to configure a Kyuubi Spark engine to use Hive Metastore.

> ... 或者kyuubi有自己的元数据管理，直接对接。

As explained before, Kyuubi has never been supposed to be a "Metastore Service", but a SQL Gateway.

**Comment by pan3793** [comment]
close as no further feedback
